Restrict access
SwedQ/dce pull request #8
Opened 2023-04-19 12:06 UTC by semrayuce

-Deny access to expensive resources

2023-04-19 12:40 UTC, podshivalovdv commented
Looks good, please also limit EMR to something like 
*.xlarge
*.2xlarge
https://aws.amazon.com/emr/pricing/?nc=sn&loc=4


https://www.quora.com/What-AWS-service-is-the-most-expensive

I didn't find what else we can easily limit. Users always can create big files or transfer a lot of data, unsure if we can easily limit that. Let's start small and expand the restrictions further.

2023-04-19 12:42 UTC, podshivalovdv requested changes

2023-04-19 12:42 UTC, podshivalovdv commented on modules/fixtures/policies/principal_policy.tmpl
> +          "*.micro"
Please allow Small and Medium EC2 instances as well

2023-04-19 12:42 UTC, podshivalovdv commented on modules/fixtures/policies/principal_policy.tmpl
> +          "db.t2.medium"
Is it necessary to state t2/t3/t4g here? Maybe the "*" can work?

2023-04-19 13:48 UTC, semrayuce commented on modules/fixtures/policies/principal_policy.tmpl
> +          "db.t2.medium"
There are large, xlarge, and 2xlarge versions of these instances. We have to specify the sizes. 
Please find the info below:
![Screenshot 2023-04-19 at 15 47 40](https://user-images.githubusercontent.com/6909124/233095552-7a9a980a-17e5-4878-bcf8-b41e3c8ec144.png)
![Screenshot 2023-04-19 at 15 47 49](https://user-images.githubusercontent.com/6909124/233095567-61b87866-538f-4731-954b-266b72f51bc5.png)
![Screenshot 2023-04-19 at 15 47 58](https://user-images.githubusercontent.com/6909124/233095579-0c172e0a-9c5f-405c-ae59-d677d96af3f5.png)

2023-04-19 13:54 UTC, semrayuce commented on modules/fixtures/policies/principal_policy.tmpl
> +          "db.t2.medium"
Also we can't limit like *.large, *.xlarge and *.2xlarge since we have 4 more expensive types(https://aws.amazon.com/rds/instance-types/)

2023-04-19 14:27 UTC, semrayuce commented on modules/fixtures/policies/principal_policy.tmpl
> +            "s3:objectSize": "1073741824" # 1GB
LimitMaxFileSize denies any attempt to upload an object to S3 buckets if the size of the object is greater than 1 GB. I wonder if we need to allow more than 1 GB?

2023-04-19 14:28 UTC, semrayuce commented on modules/fixtures/policies/principal_policy.tmpl
> +          "*.micro"
It's done!

2023-04-19 14:34 UTC, semrayuce commented
> Looks good, please also limit EMR to something like *.xlarge *.2xlarge https://aws.amazon.com/emr/pricing/?nc=sn&loc=4
> 
> https://www.quora.com/What-AWS-service-is-the-most-expensive
> 
> I didn't find what else we can easily limit. Users always can create big files or transfer a lot of data, unsure if we can easily limit that. Let's start small and expand the restrictions further.

At least we can limit the storage of large files in S3 buckets. Please find it in the latest commit.

2023-04-19 15:17 UTC, podshivalovdv requested changes

2023-04-19 15:17 UTC, podshivalovdv commented on modules/fixtures/policies/principal_policy.tmpl
> +          "db.t2.medium"
Got it

2023-04-19 15:17 UTC, podshivalovdv commented on modules/fixtures/policies/principal_policy.tmpl
> +            "s3:objectSize": "1073741824" # 1GB
Aha, nice, I think even 1GB is too much. Let's limit it down to 100Mb maybe?

2023-04-20 11:46 UTC, podshivalovdv approved these changes
Looks good!

2023-04-20 11:48 UTC, merged